%
%
englishrelfreq=[ .082 .015 .028 .043 .127 .022 .020 .061 .070 .002 .008 , ...
    .040 .024 .067 .075 .019 .001 .060 .063 .091 .028 .010 .023 .001 .020 .001]';


% following text is from Simon Singh's book "Code Book", page 32
txt1=['innovembertheenglishforcesofhenryeighthdemolishedthescottisharmy',...
      'atthebattleofsolwaymossitappearedthathenrywasonthevergeofconquering',...
      'scotlandandstealingthecrownofkingjamesfifthafterthebattlethedistraughtscottish',...
      'kingsufferedacompletementalandphysicalbreakdownandwithdrewtothe',...
      'palaceatfalklandeventhebirthofadaughtermaryjusttwoweekslatercould',...
      'notrevivetheailingkingitwasasifhehadbeenwaitingfornewsofanheirso',...
      'thathecoulddieinpeacesafeintheknowledgethathehaddonehisdutyjustaweek',...
      'aftermarysbirthkingjamesfifthstillonlythirtyyearsolddiedthebaby',...
      'princesshadbecomemaryqueenofscotsmarywasbornprematurelyandinitiallythere',...
      'wasconsiderableconcernthatshewouldnotsurviverumoursinenglandsuggested',...
      'thatthebabyhaddiedbutthiswasmerelywishfulthinkingattheenglishcourt',...
      'whichwaskeentohearanynewsthatmightdestabilisescotlandinfactmarysoongrewstrong',...
      'andhealthyandatageninemonthsshewascrownedinthechapelofstirlingcastle',...
      'surroundedbythreeearlsbearingonherbehalftheroyalcrownsceptreandsword',...
      'thefactthatqueenmarywassoyoungofferedscotlandarespitefromenglishincursions',...
      'itwouldhavebeendeemedunchivalroushadhenryattemptedtoinvadethecountryofa',...
      'recentlydeadkingnowundertheruleofaninfantqueeninsteadtheenglishkingdecided',...
      'onapolicyofwooingmaryinthehopeofarrangingamarriagebetweenherandhissonedward'];